apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-{{ .Values.cloud.provider }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sync
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            command: {{ .Values.command }}
            args: {{ .Values.args }}
            envFrom:
              - configMapRef:
                  name: {{ .Release.Name }}-config